# preload = /home/magnsi0/personal/wallpaper/WALLPAPER.png
# wallpaper = ,/home/magnsi0/personal/wallpaper/WALLPAPER.png
# Set the background to solid black (#000000)
splash = true
splash_color = 0x000000
