#!/usr/bin/env bash
RED='\033[0;31m'
NC='\033[0m'

echo -e "${RED}pulling claude/personal...${NC}"
git -C claude/personal pull

echo -e "${RED}pulling claude/work...${NC}"
git -C claude/work pull

echo -e "${RED}pulling claude...${NC}"
git -C claude pull

echo -e "${RED}pulling configs/nvim...${NC}"
git -C configs/nvim pull

echo -e "${RED}pulling dotfiles...${NC}"
git pull
